# Database Configuration
DATABASE_TYPE=${DATABASE_TYPE}
DATABASE_HOST=${DATABASE_HOST}
DATABASE_PORT=${DATABASE_PORT}
DATABASE_USER=${DATABASE_USER}
DATABASE_PASSWORD=${DATABASE_PASSWORD}
DATABASE_NAME=${DATABASE_NAME}

# Other Backend Configuration
PORT=4000
NODE_ENV=development